export enum StatisticsEnum {
    TotalUsers,
    TotalActiveUsers,
    TotalInactiveUsers,
    TotalPosts,
    TotalEvents,
    TotalChats,
    TotalKnowledgeCenterDocuments,
    AttendedEvents,
    CommentedPosts,
    LikedKnowledgeCenterDocuments,
    LikedPosts,
    PostOwners,
    SharedKnowledgeCenterDocuments,
    SharedPosts,
}