//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCE.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCE.Resource.Message_Resource", typeof(Message_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Arabic Name Is Required.
        /// </summary>
        public static string ArabicNameIsRequired {
            get {
                return ResourceManager.GetString("ArabicNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string AttachmentEntity {
            get {
                return ResourceManager.GetString("AttachmentEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Delete Cities Has Districts.
        /// </summary>
        public static string CantDeleteCitiesHasDistricts {
            get {
                return ResourceManager.GetString("CantDeleteCitiesHasDistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Delete Country Has StateRegions.
        /// </summary>
        public static string CantDeleteCountryHasStateRegions {
            get {
                return ResourceManager.GetString("CantDeleteCountryHasStateRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Delete Districts Has Clusters.
        /// </summary>
        public static string CantDeleteDistrictsHasClusters {
            get {
                return ResourceManager.GetString("CantDeleteDistrictsHasClusters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to delete a role that has users.
        /// </summary>
        public static string CantDeleteRoleHasUsers {
            get {
                return ResourceManager.GetString("CantDeleteRoleHasUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Delete StateRegions Has Cities.
        /// </summary>
        public static string CantDeleteStateRegionsHasCities {
            get {
                return ResourceManager.GetString("CantDeleteStateRegionsHasCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This region cannot be deleted. Countries have been added to it.
        /// </summary>
        public static string CantDeleteWorldRegionHasCountries {
            get {
                return ResourceManager.GetString("CantDeleteWorldRegionHasCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CityEntity {
            get {
                return ResourceManager.GetString("CityEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster.
        /// </summary>
        public static string ClusterEntity {
            get {
                return ResourceManager.GetString("ClusterEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryEntity {
            get {
                return ResourceManager.GetString("CountryEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfuly.
        /// </summary>
        public static string DefaultSave {
            get {
                return ResourceManager.GetString("DefaultSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string DistrictEntity {
            get {
                return ResourceManager.GetString("DistrictEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The English Name Is Required.
        /// </summary>
        public static string EnglishNameIsRequired {
            get {
                return ResourceManager.GetString("EnglishNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not found..
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Get Profile.
        /// </summary>
        public static string ErrorInGetProfile {
            get {
                return ResourceManager.GetString("ErrorInGetProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field In Login Operation..
        /// </summary>
        public static string FieldInLoginOperation {
            get {
                return ResourceManager.GetString("FieldInLoginOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension is not valid and available extensions are {0}.
        /// </summary>
        public static string FileExtensionNotValid {
            get {
                return ResourceManager.GetString("FileExtensionNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name can not be empty.
        /// </summary>
        public static string FileNameEmpty {
            get {
                return ResourceManager.GetString("FileNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least one file..
        /// </summary>
        public static string FilesAreRequired {
            get {
                return ResourceManager.GetString("FilesAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect OTP.
        /// </summary>
        public static string IncorrectOTP {
            get {
                return ResourceManager.GetString("IncorrectOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file module..
        /// </summary>
        public static string InvalidFileModule {
            get {
                return ResourceManager.GetString("InvalidFileModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value {0} for parameter {1}.
        /// </summary>
        public static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Name.
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You exceeded the max number of trials for this one time password please request another one..
        /// </summary>
        public static string MaxNumberOfTriesReached {
            get {
                return ResourceManager.GetString("MaxNumberOfTriesReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was not found..
        /// </summary>
        public static string MessageNotFound {
            get {
                return ResourceManager.GetString("MessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter either phone number or a name..
        /// </summary>
        public static string NameOrPhoneRequired {
            get {
                return ResourceManager.GetString("NameOrPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Id Required.
        /// </summary>
        public static string NationalIdRequired {
            get {
                return ResourceManager.GetString("NationalIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No otp was sent before for this national Id, Please login again..
        /// </summary>
        public static string NoOtpWasSentBefore {
            get {
                return ResourceManager.GetString("NoOtpWasSentBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFound.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One time password..
        /// </summary>
        public static string OtpEntity {
            get {
                return ResourceManager.GetString("OtpEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name Required.
        /// </summary>
        public static string RoleNameRequired {
            get {
                return ResourceManager.GetString("RoleNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Field..
        /// </summary>
        public static string SaveField {
            get {
                return ResourceManager.GetString("SaveField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Region.
        /// </summary>
        public static string StateRegionEntity {
            get {
                return ResourceManager.GetString("StateRegionEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send one time password..
        /// </summary>
        public static string UnableToSendOtp {
            get {
                return ResourceManager.GetString("UnableToSendOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already an admin..
        /// </summary>
        public static string UserAlreadyAnAdmin {
            get {
                return ResourceManager.GetString("UserAlreadyAnAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Already Has this Role.
        /// </summary>
        public static string UserAlreadyHasRole {
            get {
                return ResourceManager.GetString("UserAlreadyHasRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserEntity {
            get {
                return ResourceManager.GetString("UserEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName Required.
        /// </summary>
        public static string UserFullNameRequired {
            get {
                return ResourceManager.GetString("UserFullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId Required.
        /// </summary>
        public static string UserIdRequired {
            get {
                return ResourceManager.GetString("UserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Region.
        /// </summary>
        public static string WorldRegionEntity {
            get {
                return ResourceManager.GetString("WorldRegionEntity", resourceCulture);
            }
        }
    }
}
